### PR TITLE
User specified canvas impl

### PR DESCRIPTION
**Pull request by swhitf**
Hello

Great library...!  I'm using it on a project of mine and needed to be able to specify my own canvas.  I noticed it is in your backlog so I have added an implementation in this pull request.  Some notes:
- Replaced animationObj with a global map of animation objects
- Lookup is based on the id of the canvas
- User specified canvas _must_ have an id set else an exception is thrown

I've updated the demo page but not added any tests.  I could not get the tests to run on my machine and have limited experience with this stack.

Let me know if you have any comments
Cheers

### CODE REVIEW

**Comment by catdad** [comment]
@swhitf Thanks! I will take a look later today.

What sort of problem are you having with the tests? What is your setup? They are working out of the box for me on Windows on Linux, but maybe there's something I missed that I can fix. If you want, you can open a separate issue for that, so that we don't mix the two conversations.

**Comment by swhitf** [comment]
I'm on Windows 10.  I `npm installed` everything but when Puppeteer ran it complained about not being able to find Chromium.  I've not used it before and didn't have a lot of time today to dig into it.  I can have another try this week if I get some time.

**Comment by catdad** [comment]
Okay... so I got a bit busy tonight. But I dislike the idea of requiring canvases to have an `id` defined. It's just really not a pattern I prefer. So I played around with a couple of ideas and I have settled on what ended up being quite simple. Add a new method, `var myConfetti = confetti.create(canvas);`, which would allow you to create an instance of the global `confetti` launcher that will always use your canvas. The only thing I really had to do was wrap the `confetti` method and the existing `animationObj` into a function. Check out #54.

I do like your changes to the web page and would like to bring those in. Please let me know if you'd like to be involved in finishing that up and possibly adding some tests? If not, I'd be happy to pull this PR into my branch and finishing it up.

As for the tests, did you perhaps `npm install` with the `--ignore-scripts` flag? Puppeteer is supposed to pull down a version of Chromium as part of its post-install action, and I checked it out just now on my Windows 10 box.

**Comment by catdad** [comment]
Addresses #52

**Comment by swhitf** [comment]
I did think you might have an issue with the `id` requirement and I agree that it's a bit unsophisticated.  It worked for my situation and is simple to use which I is why I went that route.  I agree that your solution is better and that you should integrate it.

Thanks for your consideration however I think it would be best if you complete the remaining work since I'm not going to have any availability for another week.  I'm also in the launch phase of my side project (which is what I needed the confetti for) so that is kinda sapping my time at the moment...!

I will try and figure out why I couldn't get the tests working and get back to you, just won't be for a few days. :)

**Pull request merged**
