### PR TITLE
Added support RGB and RGBA format color

### PR DESCRIPTION
**Pull request by ulitcos**

### CODE REVIEW

**Comment by catdad** [comment]
Hello! Thanks for your contribution.

Can you tell me the value being delivered by this? Why is this feature required?

**Comment by ulitcos** [comment]
Hi!
My designer asked me to make 3 different types of confetti ([rgba(255, 255, 255, 1), rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 0.4)]), so this is my way of fulfilling his wish.

**Comment by catdad** [comment]
I am afraid that someone's wish is not itself value. Since this expands the API of the library, I would like to understand what benefits users gain by adding this feature. What are scenarios that users want to implement that make this feature required?

There are also potential issues with what you described. All colors are white with different transparency applied. But of course, confetti already change their transparency starting immediately when they are launched, which means that the color is not really ever actually used (except for a single frame at the very start), and the color `rgba(255,255,255,0.4)` will start off looking the same as `rgba(255,255,255,1)` after it has already animated about half-way. So I am not sure what scenario is really being supported here past perhaps having a very small amount of very precise particles.

Another issue of expanding the API without understanding why or what is being supported means that, once published, your designer may see that it makes largely no visible difference and decide to do a different implementation. This leaves me supporting a feature that no one wants and I don't even understand why it exists.

**Comment by ulitcos** [comment]
It is difficult for me to evaluate the designer's wishes. I specialize in a different field. Apparently, with transparency, we get a more suitable effect for us.

We use the following settings:
- gravity: 1.9
- ticks: 800
This way we avoid changing opacity.

Anyway, I can use the feature from my fork.

**Pull request closed without merging**
